# Generated by Django 4.1.2 on 2022-12-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
