# Generated by Django 4.1.2 on 2022-12-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_posts_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
